### PR TITLE
Code Cleanup. Resolves #8

### LINKED ISSUE #8: Integrate express router functionality in backend
Split up the various routes in backend/src/node.js into separate files using express router.

### PR DESCRIPTION
**Pull request by Bhavesh27**

### CODE REVIEW

**Comment by ryzbaka** [comment]
All the routes are still in a single file, kindly split them up into separate files ( one file per route)

**Comment by Bhavesh27** [comment]
> All the routes are still in a single file, kindly split them up into separate files ( one file per route)

But aren't api routes separated according to common concern. Like i created a common controller file for all user realated routes. Similarly, we can club together similar api endpoint in common controller file.

**Comment by ryzbaka** [comment]
@Bhavesh27 , in that case moving the /users routes into a separate file would be ideal.

**Comment by Bhavesh27** [comment]
> @Bhavesh27 , in that case moving the /users routes into a separate file would be ideal.

@ryzbaka Yeah that what i have done in the PR raised. Separated out all the /users api into a separate UserController file.
PR - https://github.com/ryzbaka/PyLot/pull/11

**Pull request closed without merging**
